### ISSUE TITLE
Checklist for initial release

### ISSUE THREAD

**Issue by bschneidr** [bschneidr/svrep#1]
## Desired functions
- [x] Stack replicate designs
- [x] Redistribute weights
- [x] Two diagnostic functions (one for overall and one for each column of replicate weights). Both can be given a `by` argument to stratify results.
- [x] Compare estimates using stacking

## Submit to CRAN

- [x] Group under official statistics task view
- [x] Check for issues with building manual
- [x] Run `R CMD CHECK --as-cran`
